name: srsran
base: core20
version: '20.10'
summary: srsRAN is a 4G/5G software radio suite developed by SRS.
description: srsRAN is a 4G/5G software radio suite developed by SRS.
grade: devel
confinement: strict
apps:
  srsenb:
    command: usr/bin/srsenb
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu/
  srsue:
    command: usr/bin/srsue
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu/
  srsepc:
    command: usr/bin/srsepc
    plugs:
      - home
      - network
      - network-bind
      - network-control
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu/
  install:
    command: usr/bin/srslte_install_configs.sh

layout:
  /usr/share/srsran:
    bind: $SNAP/usr/share/srslte
parts:
  srsran:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
    source: https://github.com/srsLTE/srsLTE.git
    source-type: git
    source-tag: release_20_10
    build-packages:
      - libzmq3-dev
      - build-essential
      - libmbedtls-dev
      - libboost-program-options-dev
      - libsctp-dev
      - libconfig++-dev
      - libfftw3-dev
      - net-tools
    stage-packages:
      - libzmq5
      - libboost-program-options1.71.0
      - libsctp1
      - libconfig++9v5
      - libfftw3-single3
      - libmbedcrypto3
