name: srslte
base: core20
version: '20.10'
summary: srsRAN is a 4G/5G software radio suite developed by SRS.
description: srsRAN is a 4G/5G software radio suite developed by SRS.
grade: devel
confinement: devmode
apps:
  srsenb:
    command: usr/bin/srsenb
    plugs:
      - home
      - network
      - network-bind
      - network-control
      - log-observe
      - process-control
  srsue:
    command: usr/bin/srsue
    plugs:
      - home
      - network
      - network-bind
      - network-control
  srsepc:
    command: usr/bin/srsepc
    plugs:
      - home
      - network
      - network-bind
      - network-control

layout:
  /usr/share/srslte:
    bind: $SNAP/usr/share/srslte
  /etc/srslte:
    bind: $SNAP_DATA/etc/srslte
parts: 
  srslte:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - -DENABLE_ASAN=True
      - -DCMAKE_INSTALL_PREFIX=/usr
    source: https://github.com/srsLTE/srsLTE.git
    source-type: git
    source-tag: release_20_10_1
    build-packages:
      - libzmq3-dev
      - libmbedtls-dev
      - libboost-program-options-dev
      - libsctp-dev
      - libconfig++-dev
      - libfftw3-dev
    stage-packages:
      - libzmq5
      - libboost-program-options1.71.0
      - libsctp1
      - libfftw3-single3
      - libmbedcrypto3
      - libconfig++9v5
      - libasan5
    prime:
      - -usr/include
