name: srsran
base: core20
version: '22.10'
summary: srsRAN is a 4G/5G software radio suite developed by SRS.
description: |
  srsRAN is a free and open-source 4G and 5G software radio suite.

  Featuring both UE and eNodeB/gNodeB applications, srsRAN can be used with third-party core network solutions to build complete end-to-end mobile wireless networks. For more information, see https://www.srsran.com/.

  The srsRAN suite currently includes:
  - srsUE: a full-stack 4G and 5G NSA / SA UE application
  - srsENB: a full-stack 4G eNodeB with 5G NSA / SA gNodeB capabilities
  - srsEPC: a light-weight 4G EPC implementation with MME, HSS and S/P-GW

  All srsRAN software runs in linux with off-the-shelf compute and radio hardware.
grade: devel
confinement: devmode
icon: snap/local/srsran.png
website: https://www.srsran.com/
source-code: https://github.com/canonical/srsran-snap
license: Apache-2.0

apps:
  srsenb:
    command: usr/bin/srsenb
  srsue:
    command: usr/bin/srsue
  srsepc:
    command: usr/bin/srsepc
layout:
  /usr/share/srsran:
    bind: $SNAP/config
  /etc/srsran:
    bind: $SNAP/config
parts:
  config:
    plugin: dump
    source: local/
    organize:
      '*': config/
  srsran:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - -DENABLE_ASAN=True
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DAUTO_DETECT_ISA=OFF
      - -DHAVE_SSE=True
      - -DHAVE_AVX=True
    source: https://github.com/srsran/srsRAN
    source-type: git
    source-tag: release_22_10
    build-packages:
      - cmake
      - build-essential
      - libzmq3-dev
      - libmbedtls-dev
      - libboost-program-options-dev
      - libsctp-dev
      - libconfig++-dev
      - libfftw3-dev
    stage-packages:
      - libzmq5
      - libboost-program-options1.71.0
      - libsctp1
      - libfftw3-single3
      - libmbedcrypto3
      - libconfig++9v5
      - libasan5
    override-build: |
      set -x
      pushd $SNAPCRAFT_PART_SRC
      sed -ie 's/native/x86_64/g' CMakeLists.txt
      popd
      snapcraftctl build
    prime:
      - -usr/include
