name: srsran
base: core20
version: '20.10'
summary: srsRAN is a 4G/5G software radio suite developed by SRS.
description: srsRAN is a 4G/5G software radio suite developed by SRS.
grade: devel
confinement: devmode
apps:
  srsenb:
    command: usr/bin/srsenb
  srsue:
    command: usr/bin/srsue
  srsepc:
    command: usr/bin/srsepc
layout:
  /usr/share/srsran:
    bind: $SNAP/usr/share/srsran
  /etc/srsran:
    bind: $SNAP/usr/share/srsran
parts: 
  srsran:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - -DENABLE_ASAN=True
      - -DCMAKE_INSTALL_PREFIX=/usr
    source: https://github.com/srsran/srsRAN
    source-type: git
    source-tag: release_22_10
    build-packages:
      - cmake
      - build-essential
      - libzmq3-dev
      - libmbedtls-dev
      - libboost-program-options-dev
      - libsctp-dev
      - libconfig++-dev
      - libfftw3-dev
    stage-packages:
      - libzmq5
      - libboost-program-options1.71.0
      - libsctp1
      - libfftw3-single3
      - libmbedcrypto3
      - libconfig++9v5
      - libasan5
    prime:
      - -usr/include
    organize:
      ./usr/share/srsran/ue.conf.example: ./usr/share/srsran/ue.conf
      ./usr/share/srsran/drb.conf.example: ./usr/share/srsran/drb.conf
      ./usr/share/srsran/enb.conf.example: ./usr/share/srsran/enb.conf
      ./usr/share/srsran/epc.conf.example: ./usr/share/srsran/epc.conf
      ./usr/share/srsran/rr.conf.example: ./usr/share/srsran/rr.conf
      ./usr/share/srsran/sib.conf.example: ./usr/share/srsran/sib.conf
      ./usr/share/srsran/user_db.csv.example: ./usr/share/srsran/user_db.csv
      ./usr/share/srsran/rb.conf.example: ./usr/share/srsran/rb.conf
