name: srsran
base: core20
version: '20.10'
summary: srsRAN is a 4G/5G software radio suite developed by SRS.
description: |
  srsRAN is a free and open-source 4G and 5G software radio suite.

  Featuring both UE and eNodeB/gNodeB applications, srsRAN can be used with third-party core network solutions to build complete end-to-end mobile wireless networks. For more information, see www.srsran.com.

  The srsRAN suite currently includes:
  - srsUE: a full-stack 4G and 5G NSA / SA UE application
  - srsENB: a full-stack 4G eNodeB with 5G NSA / SA gNodeB capabilities
  - srsEPC: a light-weight 4G EPC implementation with MME, HSS and S/P-GW

  All srsRAN software runs in linux with off-the-shelf compute and radio hardware.
grade: devel
confinement: classic
icon: snap/srsran.png
website: https://www.srslte.com/
source-code: https://github.com/canonical/srsran-snap
license: Apache-2.0

apps:
  srsenb:
    command: usr/bin/srsenb
  srsue:
    command: usr/bin/srsue
  srsepc:
    command: usr/bin/srsepc
layout:
  /usr/share/srslte:
    bind: $SNAP/usr/share/srslte
  /etc/srslte:
    bind: $SNAP/usr/share/srslte
parts: 
  srslte:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - -DENABLE_ASAN=True
      - -DCMAKE_INSTALL_PREFIX=/usr
    source: https://github.com/srsLTE/srsLTE.git
    source-type: git
    source-tag: release_20_10_1
    build-packages:
      - libzmq3-dev
      - libmbedtls-dev
      - libboost-program-options-dev
      - libsctp-dev
      - libconfig++-dev
      - libfftw3-dev
    stage-packages:
      - libzmq5
      - libboost-program-options1.71.0
      - libsctp1
      - libfftw3-single3
      - libmbedcrypto3
      - libconfig++9v5
      - libasan5
    prime:
      - -usr/include
    organize:
      ./usr/share/srslte/ue.conf.example: ./usr/share/srslte/ue.conf
      ./usr/share/srslte/drb.conf.example: ./usr/share/srslte/drb.conf
      ./usr/share/srslte/enb.conf.example: ./usr/share/srslte/enb.conf
      ./usr/share/srslte/epc.conf.example: ./usr/share/srslte/epc.conf
      ./usr/share/srslte/rr.conf.example: ./usr/share/srslte/rr.conf
      ./usr/share/srslte/sib.conf.example: ./usr/share/srslte/sib.conf
      ./usr/share/srslte/user_db.csv.example: ./usr/share/srslte/user_db.csv
