name: push-to-branch
on:
  push:
    branches:
      - "**"
      - "!main"

jobs:

  build-snap:
    name: Build srsRAN snap
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: snapcore/action-build@v1
