name: merge-to-main
on:
  push:
    branches:
      - main

jobs:

  build-and-publish-snap:
    name: Build and publish srsRAN snap
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: snapcore/action-build@v1
        id: build
      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.SNAPSTORE_LOGIN }}
          snap: ${{ steps.build.outputs.snap }}
          release: edge
